MISSING_REQUEST_BODY = 'Отсутствует тело запроса'
REQUIRED_FIELD = '"url" является обязательным полем!'
SHORT_LINK_INVALID_NAME = 'Указано недопустимое имя для короткой ссылки'
ALLOWED_CHARACTERS = '^[A-Za-z0-9]*$'
URL_IS_TAKEN = 'Имя %s уже занято.'
ID_NOT_FOUND = 'Указанный id не найден'
